# Generated by Django 6.0.5 on 2026-06-02 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_order_status_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('service_email', models.EmailField(blank=True, help_text='Email pro denní report produktů s nulovou cenou nebo chybnou konfigurací.', max_length=254, null=True)),
                ('shop_name', models.CharField(default='FreshBooks', max_length=128)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('hide_zero_price_products', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nastavení obchodu',
                'verbose_name_plural': 'Nastavení obchodu',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
