# Generated by Django 6.0.5 on 2026-06-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_order_external_order_id_order_payment_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
