# Generated by Django 6.0.5 on 2026-06-03 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_cover_images_book_publisher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='audio_sample_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='book',
            name='new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='preview_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.CharField(blank=True, help_text='Např. Novinka, Akce, Doporučeno', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bankovní převod'), ('qr_payment', 'Platba přes QR'), ('benefit_card', 'Benefitní karta'), ('invoice', 'Platba na fakturu')], max_length=32),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField()),
                ('approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
