# Generated by Django 6.0.5 on 2026-06-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_blogpost_book_audio_sample_url_book_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cart_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('converted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
